package es.excentia.sonar.plugins.tattletale;

import java.util.List;

import org.htmlparser.NodeFilter;
import org.htmlparser.Parser;
import org.htmlparser.filters.TagNameFilter;
import org.htmlparser.util.NodeList;
import org.htmlparser.util.ParserException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.sonar.api.CoreProperties;
import org.sonar.api.batch.DependedUpon;
import org.sonar.api.batch.Sensor;
import org.sonar.api.batch.SensorContext;
import org.sonar.api.config.Settings;
import org.sonar.api.measures.Measure;
import org.sonar.api.measures.Metric;
import org.sonar.api.resources.Project;

import es.excentia.sonar.plugins.tattletale.util.TattletaleUtil;

/**
 * This class implements a Sensor to calculate the TattletaleMetrics metrics
 */
public class TattletaleSensor implements Sensor {

  private static final Logger LOG = LoggerFactory.getLogger(TattletaleUtil.class);

  private final String serverURL;

  private static final int TWO = 2;
  private static final int FOUR = 4;

  /**
   * @return the serverURL
   */
  public final String getServerURL() {
    return serverURL;
  }

  /**
   * Constructor
   * 
   * @param settings
   *          Sonar settings
   */
  public TattletaleSensor(Settings settings) {
    this.serverURL = settings.getString(CoreProperties.SERVER_BASE_URL);
  }

  /**
   * Should this sensor be executed on Sonar?
   */
  public final boolean shouldExecuteOnProject(Project project) {
    boolean execute = false;

    // only if it's a java project
    if (project.getLanguage().getKey().equals("java")) {
      execute = true;
    }
    return execute;
  }

  /**
   * 
   * @return Metrics list implemented
   */
  @DependedUpon
  public final List<Metric> getDependedMetrics() {
    return TattletaleMetrics.getMetricsStatic();
  }

  public final void saveTotalJars(SensorContext context, String htmlData) {
    // Creates the parser
    Parser parser = Parser.createParser(htmlData, null);

    try {
      // Parses all HTML page
      NodeList page = parser.parse(null);

      NodeFilter filter = new TagNameFilter("td");
      Integer total = TattletaleUtil.removeNodesThatMatch(page, filter, false);

      total = (total - FOUR) / TWO;

      // save measure
      context.saveMeasure(TattletaleMetrics.TOTALJARS, total.doubleValue());

    } catch (ParserException exception) {
      LOG.error(exception.getMessage());
    }
  }

  /**
   * Stores into the context 2 metrics: HTML generated by Tattletale as a DATA metric (after processing), and the metric value associated
   * 
   * @param context
   *          Sensor context
   * @param htmlData
   *          HTML generated by Tattletale
   * @param htmlMetric
   *          HTML metric
   * @param valueMetric
   *          Metric associated
   * @param expression
   *          String to find into the HTML to calculate the metric associated
   */
  public final void saveTattletaleMetric(SensorContext context, String htmlData, Metric htmlMetric, Metric valueMetric, String expression) {
    // Creates the parser
    Parser parser = Parser.createParser(htmlData, null);

    String data = "";

    try {
      // Parses all HTML page
      NodeList page = parser.parse(null);

      // Puts CSS style
      NodeFilter filter = new TagNameFilter("link");
      String style = getServerURL() + "/static/sonarTattletalePlugin/tattletale-style.css";
      TattletaleUtil.putCssStyle(page, filter, style);

      // Removing title
      filter = new TagNameFilter("h1");
      TattletaleUtil.removeNodesThatMatch(page, filter, true);

      // Removing Main link
      filter = new TagNameFilter("a");
      TattletaleUtil.removeNodesThatMatch(page, filter, true);

      // Removing links
      TattletaleUtil.changeNodesToText(page, filter);

      // after removing
      data = page.toHtml();

      // save measure
      context.saveMeasure(new Measure(htmlMetric, data));

      // obtaining metric
      filter = new TagNameFilter("td");
      Integer metricValue = TattletaleUtil.countNumberOfTimesAppearsText(page, filter, expression);

      if (valueMetric.equals(TattletaleMetrics.SIGNEDJARS)) {
        metricValue--;
      }

      // save measure
      context.saveMeasure(valueMetric, metricValue.doubleValue());

    } catch (ParserException exception) {
      LOG.error(exception.getMessage());
    }
  }

  /**
   * Obtains information about the Sonar project and used to save measures
   * 
   * @param resource
   *          the resource where the method is executed (project, class...)
   * @param context
   *          the decorator context
   */
  public final void analyse(Project project, SensorContext context) {

    String directory = (String) project.getProperty("tattletale-destination-directory");

    if (directory != null) {

      // TOTAL JARs
      String data = TattletaleUtil.fileToString(directory + "/unusedjar/index.html");
      saveTotalJars(context, data);

      // UNUSED JARs
      data = TattletaleUtil.fileToString(directory + "/unusedjar/index.html");
      saveTattletaleMetric(context, data, TattletaleMetrics.HTMLUNUSEDJARS, TattletaleMetrics.UNUSEDJARS, "No");

      // SIGNED JARs
      data = TattletaleUtil.fileToString(directory + "/sign/index.html");
      saveTattletaleMetric(context, data, TattletaleMetrics.HTMLSIGNEDJARS, TattletaleMetrics.SIGNEDJARS, "Signed");
    }
  }
}
